import type { Product } from "./types"

export const mockProducts: Product[] = [
  // Customized Magazines
  {
    id: "mag-1",
    name: "Wedding Magazine",
    slug: "wedding-magazine",
    description:
      "Personalized wedding planning magazine with custom layouts, designs, and colors. Perfect for documenting your special day.",
    price: 24.99,
    category: "magazines",
    image: "/wedding-magazine-cover.jpg",
    stock: 50,
    customizable: true,
    colors: ["Blush Pink", "Sage Green", "Lavender", "Cream"],
    designs: ["Modern", "Classic", "Romantic", "Minimalist"],
    keywords: ["wedding magazine", "custom wedding planner", "personalized wedding", "wedding memories"],
    seoTitle: "Custom Wedding Magazine - Personalized Wedding Planner",
    seoDescription:
      "Create your personalized wedding magazine with custom colors and designs. Perfect for planning and documenting your special day.",
  },
  {
    id: "mag-2",
    name: "Birthday Magazine",
    slug: "birthday-magazine",
    description:
      "Celebrate special birthdays with custom photo layouts and memory pages. Create lasting memories of milestone moments.",
    price: 19.99,
    category: "magazines",
    image: "/birthday-magazine-celebration.jpg",
    stock: 60,
    customizable: true,
    colors: ["Coral", "Mint", "Peach", "Sky Blue"],
    designs: ["Fun", "Elegant", "Playful", "Artistic"],
    keywords: ["birthday magazine", "custom birthday planner", "birthday memories", "personalized birthday gift"],
    seoTitle: "Custom Birthday Magazine - Personalized Birthday Planner",
    seoDescription:
      "Create a personalized birthday magazine to celebrate and document special birthday moments with custom designs.",
  },
  {
    id: "mag-3",
    name: "Couple Magazine",
    slug: "couple-magazine",
    description:
      "Celebrate your relationship with a custom couple magazine. Perfect for anniversaries, engagements, or just documenting your love story.",
    price: 22.99,
    category: "magazines",
    image: "/couple-love-story-magazine.jpg",
    stock: 45,
    customizable: true,
    colors: ["Rose Gold", "Blush", "Champagne", "Burgundy"],
    designs: ["Romantic", "Modern", "Elegant", "Vintage"],
    keywords: ["couple magazine", "anniversary magazine", "love story", "personalized couple gift"],
    seoTitle: "Custom Couple Magazine - Personalized Anniversary Gift",
    seoDescription:
      "Create a beautiful personalized couple magazine to celebrate your love story with custom designs and layouts.",
  },
  {
    id: "mag-4",
    name: "Friendship Magazine",
    slug: "friendship-magazine",
    description:
      "Celebrate friendships with custom photo layouts and memories. Perfect for best friends and group celebrations.",
    price: 19.99,
    category: "magazines",
    image: "/friendship-magazine-memories.jpg",
    stock: 60,
    customizable: true,
    colors: ["Coral", "Mint", "Peach", "Sky Blue"],
    designs: ["Fun", "Elegant", "Playful", "Artistic"],
    keywords: ["friendship magazine", "best friend gift", "friendship memories", "custom friend magazine"],
    seoTitle: "Custom Friendship Magazine - Best Friend Gift",
    seoDescription: "Create a personalized friendship magazine to celebrate and document your best friend memories.",
  },
  {
    id: "mag-5",
    name: "Travel Magazine",
    slug: "travel-magazine",
    description:
      "Document your adventures with custom travel magazine. Perfect for vacation memories and travel stories.",
    price: 22.99,
    category: "magazines",
    image: "/travel-adventure-magazine.jpg",
    stock: 45,
    customizable: true,
    colors: ["Terracotta", "Navy", "Gold", "Teal"],
    designs: ["Adventure", "Luxury", "Minimalist", "Vintage"],
    keywords: ["travel magazine", "vacation planner", "travel memories", "adventure journal"],
    seoTitle: "Custom Travel Magazine - Personalized Vacation Planner",
    seoDescription: "Create a personalized travel magazine to document your adventures and vacation memories.",
  },
  {
    id: "mag-6",
    name: "Anniversary Magazine",
    slug: "anniversary-magazine",
    description: "Celebrate years of love and memories with a custom anniversary magazine. Perfect for any milestone.",
    price: 24.99,
    category: "magazines",
    image: "/anniversary-celebration-magazine.jpg",
    stock: 40,
    customizable: true,
    colors: ["Gold", "Silver", "Rose Gold", "Champagne"],
    designs: ["Elegant", "Romantic", "Classic", "Modern"],
    keywords: ["anniversary magazine", "anniversary gift", "celebration magazine", "personalized anniversary"],
    seoTitle: "Custom Anniversary Magazine - Personalized Anniversary Gift",
    seoDescription: "Create a beautiful personalized anniversary magazine to celebrate your special milestone.",
  },

  // Journals
  {
    id: "journal-1",
    name: "Daily Journal",
    slug: "daily-journal",
    description: "Guided daily journal for reflection and mindfulness. Includes prompts and spaces for daily thoughts.",
    price: 14.99,
    category: "journals",
    image: "/daily-journal-mindfulness.jpg",
    stock: 100,
    customizable: true,
    colors: ["Lavender", "Blush", "Mint", "Cream"],
    keywords: ["daily journal", "mindfulness journal", "reflection journal", "personal diary"],
    seoTitle: "Daily Journal - Guided Mindfulness & Reflection",
    seoDescription: "Beautiful daily journal with guided prompts for mindfulness, reflection, and personal growth.",
  },
  {
    id: "journal-2",
    name: "Reading Journal",
    slug: "reading-journal",
    description: "Track your reading journey with custom layouts. Perfect for book lovers and avid readers.",
    price: 12.99,
    category: "journals",
    image: "/reading-journal-book-tracker.jpg",
    stock: 80,
    customizable: true,
    colors: ["Sage", "Terracotta", "Navy", "Rose"],
    keywords: ["reading journal", "book journal", "book tracker", "reading log"],
    seoTitle: "Reading Journal - Book Tracker & Review Journal",
    seoDescription: "Track your reading journey with a personalized reading journal. Perfect for book lovers.",
  },
  {
    id: "journal-3",
    name: "Gratitude Journal",
    slug: "gratitude-journal",
    description: "Daily gratitude practice with beautiful prompts. Cultivate positivity and mindfulness.",
    price: 13.99,
    category: "journals",
    image: "/gratitude-journal-positive-thinking.jpg",
    stock: 90,
    customizable: true,
    colors: ["Gold", "Blush", "Mint", "Lavender"],
    keywords: ["gratitude journal", "positivity journal", "mindfulness", "daily gratitude"],
    seoTitle: "Gratitude Journal - Daily Positivity & Mindfulness",
    seoDescription: "Beautiful gratitude journal with daily prompts to cultivate positivity and mindfulness.",
  },

  // Scrapbooks
  {
    id: "scrap-1",
    name: "Baby Scrapbook",
    slug: "baby-scrapbook",
    description:
      "Preserve precious baby memories with custom layouts. Perfect for documenting milestones and special moments.",
    price: 18.99,
    category: "scrapbooks",
    image: "/baby-scrapbook-memories.jpg",
    stock: 40,
    customizable: true,
    colors: ["Soft Yellow", "Pale Pink", "Mint", "Cream"],
    keywords: ["baby scrapbook", "baby memories", "newborn scrapbook", "baby milestone"],
    seoTitle: "Baby Scrapbook - Preserve Precious Baby Memories",
    seoDescription: "Create a beautiful baby scrapbook to preserve precious memories and milestones.",
  },
  {
    id: "scrap-2",
    name: "Couples Scrapbook",
    slug: "couples-scrapbook",
    description:
      "Celebrate your love story with custom couple scrapbook. Perfect for anniversaries and special moments.",
    price: 21.99,
    category: "scrapbooks",
    image: "/couples-love-story-scrapbook.jpg",
    stock: 35,
    customizable: true,
    colors: ["Rose Gold", "Blush", "Champagne", "Burgundy"],
    keywords: ["couples scrapbook", "love story", "anniversary scrapbook", "relationship memories"],
    seoTitle: "Couples Scrapbook - Celebrate Your Love Story",
    seoDescription: "Create a personalized couples scrapbook to celebrate and document your love story.",
  },
  {
    id: "scrap-3",
    name: "Friendship Scrapbook",
    slug: "friendship-scrapbook",
    description: "Capture friendship moments with custom designs. Perfect for best friends and group memories.",
    price: 17.99,
    category: "scrapbooks",
    image: "/friendship-scrapbook-memories.jpg",
    stock: 50,
    customizable: true,
    colors: ["Rainbow", "Pastel Mix", "Neon", "Earth Tones"],
    keywords: ["friendship scrapbook", "best friend memories", "group scrapbook", "friend gift"],
    seoTitle: "Friendship Scrapbook - Celebrate Best Friend Memories",
    seoDescription: "Create a personalized friendship scrapbook to celebrate and document your best friend memories.",
  },

  // Tools & Supplies
  {
    id: "tool-1",
    name: "Decorative Tape Set",
    slug: "decorative-tape-set",
    description: "Set of 12 decorative washi tapes in various pastel designs. Perfect for scrapbooking and crafting.",
    price: 9.99,
    category: "tools",
    image: "/decorative-washi-tape-set.jpg",
    stock: 200,
    customizable: false,
    keywords: ["washi tape", "decorative tape", "craft tape", "scrapbook supplies"],
    seoTitle: "Decorative Washi Tape Set - Craft Supplies",
    seoDescription: "Beautiful set of 12 decorative washi tapes in pastel colors for scrapbooking and crafting.",
  },
  {
    id: "tool-2",
    name: "Highlighter Set",
    slug: "highlighter-set",
    description: "Pastel highlighters in 8 beautiful colors. Perfect for journaling and note-taking.",
    price: 7.99,
    category: "tools",
    image: "/pastel-highlighter-markers.jpg",
    stock: 150,
    customizable: false,
    keywords: ["highlighters", "pastel markers", "journal supplies", "craft markers"],
    seoTitle: "Pastel Highlighter Set - Journal & Craft Supplies",
    seoDescription: "Set of 8 beautiful pastel highlighters perfect for journaling, note-taking, and crafting.",
  },
  {
    id: "tool-3",
    name: "Sticky Notes Collection",
    slug: "sticky-notes-collection",
    description: "Assorted sticky notes in pastel colors and shapes. Perfect for organizing and decorating.",
    price: 6.99,
    category: "tools",
    image: "/pastel-sticky-notes-collection.jpg",
    stock: 180,
    customizable: false,
    keywords: ["sticky notes", "pastel notes", "office supplies", "craft supplies"],
    seoTitle: "Pastel Sticky Notes Collection - Office & Craft Supplies",
    seoDescription: "Assorted pastel sticky notes in various colors and shapes for organizing and decorating.",
  },
  {
    id: "tool-4",
    name: "Stamp & Sticker Set",
    slug: "stamp-sticker-set",
    description: "Beautiful stamps and stickers for decoration. Perfect for scrapbooking and journaling.",
    price: 11.99,
    category: "tools",
    image: "/placeholder.svg?height=300&width=300",
    stock: 120,
    customizable: false,
    keywords: ["stamps", "stickers", "scrapbook supplies", "craft decorations"],
    seoTitle: "Stamp & Sticker Set - Scrapbook & Craft Supplies",
    seoDescription: "Beautiful collection of decorative stamps and stickers for scrapbooking and journaling.",
  },
  {
    id: "tool-5",
    name: "Gel Pen Collection",
    slug: "gel-pen-collection",
    description: "Premium gel pens in 20 pastel shades. Perfect for writing and decorating.",
    price: 13.99,
    category: "tools",
    image: "/placeholder.svg?height=300&width=300",
    stock: 100,
    customizable: false,
    keywords: ["gel pens", "pastel pens", "writing pens", "craft pens"],
    seoTitle: "Premium Pastel Gel Pen Collection - Writing & Craft",
    seoDescription: "Set of 20 premium gel pens in beautiful pastel shades for writing and crafting.",
  },
]
